[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "read", path = "./" }]

[fuzz]
# runs = 1_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
