secret = [
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x13",
  "0x37",
]
receiver = "0xbabe"
key = [
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
]
nullifier = [
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x00",
  "0x22",
  "0x22",
  "0x44",
  "0x44",
  "0x88",
  "0x88",
]
nodes = [
  "0xad",
  "0x32",
  "0x28",
  "0xb6",
  "0x76",
  "0xf7",
  "0xd3",
  "0xcd",
  "0x42",
  "0x84",
  "0xa5",
  "0x44",
  "0x3f",
  "0x17",
  "0xf1",
  "0x96",
  "0x2b",
  "0x36",
  "0xe4",
  "0x91",
  "0xb3",
  "0x0a",
  "0x40",
  "0xb2",
  "0x40",
  "0x58",
  "0x49",
  "0xe5",
  "0x97",
  "0xba",
  "0x5f",
  "0xb5",
  "0xb4",
  "0xc1",
  "0x19",
  "0x51",
  "0x95",
  "0x7c",
  "0x6f",
  "0x8f",
  "0x64",
  "0x2c",
  "0x4a",
  "0xf6",
  "0x1c",
  "0xd6",
  "0xb2",
  "0x46",
  "0x40",
  "0xfe",
  "0xc6",
  "0xdc",
  "0x7f",
  "0xc6",
  "0x07",
  "0xee",
  "0x82",
  "0x06",
  "0xa9",
  "0x9e",
  "0x92",
  "0x41",
  "0x0d",
  "0x30",
  "0x21",
  "0xdd",
  "0xb9",
  "0xa3",
  "0x56",
  "0x81",
  "0x5c",
  "0x3f",
  "0xac",
  "0x10",
  "0x26",
  "0xb6",
  "0xde",
  "0xc5",
  "0xdf",
  "0x31",
  "0x24",
  "0xaf",
  "0xba",
  "0xdb",
  "0x48",
  "0x5c",
  "0x9b",
  "0xa5",
  "0xa3",
  "0xe3",
  "0x39",
  "0x8a",
  "0x04",
  "0xb7",
  "0xba",
  "0x85",
  "0xe5",
  "0x87",
  "0x69",
  "0xb3",
  "0x2a",
  "0x1b",
  "0xea",
  "0xf1",
  "0xea",
  "0x27",
  "0x37",
  "0x5a",
  "0x44",
  "0x09",
  "0x5a",
  "0x0d",
  "0x1f",
  "0xb6",
  "0x64",
  "0xce",
  "0x2d",
  "0xd3",
  "0x58",
  "0xe7",
  "0xfc",
  "0xbf",
  "0xb7",
  "0x8c",
  "0x26",
  "0xa1",
  "0x93",
  "0x44",
]
root = [
  "0x88",
  "0x00",
  "0x30",
  "0x85",
  "0xd9",
  "0x42",
  "0xae",
  "0xd6",
  "0x6b",
  "0xad",
  "0xd8",
  "0xd8",
  "0xa2",
  "0xe3",
  "0xd9",
  "0x28",
  "0xaa",
  "0x7d",
  "0x18",
  "0x66",
  "0xd0",
  "0xd4",
  "0x4b",
  "0x28",
  "0xe6",
  "0x60",
  "0xa1",
  "0x65",
  "0x79",
  "0xbf",
  "0x38",
  "0x81",
]
